pass cargo args to idl generation
otter-sec/anchor pull request #3059
Opened 2024-06-27 14:24 UTC by biryukovmaxim

closes #3054

2024-06-27 15:03 UTC, acheroncrypto requested changes
Thanks, it looks great other than the breaking change (new parameter).

2024-06-27 15:03 UTC, acheroncrypto commented on idl/src/build.rs
> +    args.extend(["--", "--show-output", "--quiet"]);
Nit: [`args()`](https://doc.rust-lang.org/std/process/struct.Command.html#method.args) method extends the previous arguments on each call, so no need to declare separately and manually extend.

```rs
Command::new("cargo")
        .args([
            &toolchain,
            "test",
            "__anchor_private_print_idl",
            "--features",
            "idl-build",
        ])
        .args(cargo_args)
        .args(["--", "--show-output", "--quiet"])
```

2024-06-27 20:24 UTC, acheroncrypto reviewed
Thanks! One last thing before we merge, could you note this feature in the [CHANGELOG](https://github.com/coral-xyz/anchor/blob/5f1f72c511102ad49b0f4b9361efd714b6187e13/CHANGELOG.md#features)?

2024-06-28 10:14 UTC, biryukovmaxim commented
> Thanks! One last thing before we merge, could you note this feature in the [CHANGELOG](https://github.com/coral-xyz/anchor/blob/5f1f72c511102ad49b0f4b9361efd714b6187e13/CHANGELOG.md#features)?

[done](https://github.com/coral-xyz/anchor/pull/3059/commits/1eabcdc2890dea42d6816b84da49730bb045db9f)

2024-06-28 10:43 UTC, acheroncrypto approved these changes
Thank you!

2024-06-28 10:44 UTC, merged

2025-08-01 17:04 UTC, Henry-E commented
closes: 1987