feat: cli completions + clap version bump to v4.5.17
otter-sec/anchor pull request #3251
Opened 2024-09-15 01:47 UTC by zilayo

Small QoL improvement by introducing CLI completions for Anchor.

Instead of repeatedly using `anchor --help`, we can now use `anchor ` + tab to generate completions.

This adds the `clap_completions` dependency to Anchor.
clap_completions uses clap v4.5.17, so the clap version used in Anchor has also been bumped.

There are no breaking changes between the currently used v4.2.4 and v4.5.17 - mainly just performance + bug fixes (https://github.com/clap-rs/clap/blob/master/CHANGELOG.md)

<img width="1099" alt="image" src="https://github.com/user-attachments/assets/bebe80de-7ac0-4474-a5ca-3e4d7891b8d1">
<img width="532" alt="image" src="https://github.com/user-attachments/assets/66985c4a-bcc7-423c-9b2c-65d9f57fbb5c">

2024-09-15 21:31 UTC, acheroncrypto requested changes
This is very helpful, thanks for adding it and extra thanks for adding the documentation too.

Just some nits and we can get this in.

2024-09-15 21:31 UTC, acheroncrypto commented on cli/src/lib.rs
> +            generate(
Nit: `generate` is pretty generic for this file — could you use its full path `clap_complete::generate` instead?
```suggestion
            clap_complete::generate(
```

2024-09-15 21:31 UTC, acheroncrypto commented on avm/src/main.rs
> +            generate(shell, &mut Cli::command(), "avm", &mut std::io::stdout());
Same here:
```suggestion
            clap_complete::generate(shell, &mut Cli::command(), "avm", &mut std::io::stdout());
```

2024-09-15 21:31 UTC, acheroncrypto commented on CHANGELOG.md
> +- cli: Added completions command to generate shell completions via the clap_complete crate ([#3251](https://github.com/coral-xyz/anchor/pull/3251)).
```suggestion
- cli: Add completions command to generate shell completions via the `clap_complete` crate ([#3251](https://github.com/coral-xyz/anchor/pull/3251)).
```

2024-09-15 22:28 UTC, zilayo commented
> This is very helpful, thanks for adding it and extra thanks for adding the documentation too.
> 
> Just some nits and we can get this in.

all nits fixed!

2024-09-16 12:54 UTC, acheroncrypto approved these changes
Thanks!

2024-09-16 12:55 UTC, merged