Add interest bearing mint extension and transfer memo extension
otter-sec/anchor pull request #3278
Opened 2024-09-25 21:06 UTC by Bhargavamacha

2024-09-26 10:34 UTC, acheroncrypto requested changes
Thanks, it's looking great, but it would be better if we had a test case for this in [the `token-extensions` tests](https://github.com/coral-xyz/anchor/tree/ef542f5679d0d2148e756e706fe0d28565252398/tests/spl/token-extensions).

It would also be helpful to mention feature in the [CHANGELOG](https://github.com/coral-xyz/anchor/blob/ef542f5679d0d2148e756e706fe0d28565252398/CHANGELOG.md#features).

2024-10-14 13:54 UTC, Bhargavamacha commented
@acheroncrypto updated tests and added to CHANGELOG

2025-03-12 12:16 UTC, tiago18c commented
What is currently blocking this from being merged?

2025-03-21 19:34 UTC, Bhargavamacha commented
nothing from side @acheroncrypto could you have a look

2026-04-15 01:53 UTC, jamie-osec commented
I believe this needs updating for V1, including moving the changelog entry to the correct location

2026-04-24 12:10 UTC, jamie-osec commented
Closed for #4464

2026-04-24 12:10 UTC, closed without merging